### ISSUE TITLE
A couple of issues

### ISSUE THREAD

**Issue by segeljakt** [CAD97/pegcel#4] opened 2019-05-20 15:21 UTC
I'm trying to create a simple parser for parsing structs/enums/fields/variants that have `"..."` as the identifier, e.g.:

```rust
struct ... ;
struct ... { ... }
struct ... ( ... );
enum ... ;
enum ... { ... }
enum ... { ... { ... } }
enum ... { ... ( ... ) }
```
This is my code, I manually parse braced/parenthesized rules and use a grammar to parse the rest.
```rust
#![allow(clippy::eval_order_dependence)]

use {proc_macro2::TokenStream, quote::*, syn::parse::*};

#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub struct Braced<T> {
    pub brace: syn::token::Brace,
    pub value: T,
}

impl<T: Parse> Parse for Braced<T> {
    fn parse(input: ParseStream) -> Result<Self> {
        let content;
        Ok(Braced {
            brace: syn::braced!(content in input),
            value: content.parse()?,
        })
    }
}

impl<T: ToTokens> ToTokens for Braced<T> {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        self.brace
            .surround(tokens, |tokens| self.value.to_tokens(tokens));
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub struct Parenthesized<T> {
    pub paren: syn::token::Paren,
    pub value: T,
}

impl<T: Parse> Parse for Parenthesized<T> {
    fn parse(input: ParseStream) -> Result<Self> {
        let content;
        Ok(Parenthesized {
            paren: syn::parenthesized!(content in input),
            value: content.parse()?,
        })
    }
}

impl<T: ToTokens> ToTokens for Parenthesized<T> {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        self.paren
            .surround(tokens, |tokens| self.value.to_tokens(tokens));
    }
}

pegcel_macros::pegcel_syn! {
    use syn

    Grammar: {
        templates:     Item*
        items:         syn::Item*
    }

    Item: {
        / Struct:      ItemStruct
        / Enum:        ItemEnum
    }

    ItemStruct: {
        attrs:         syn::Attribute*
        vis:           syn::Visibility
        struct_token:  syn::token::Struct
        ident:         "..."
        field:         WrappedField
        semi_token:    syn::token::Semi?
    }

    WrappedField: {
        / Named:       {Braced<Field>}
        / Unnamed:     {Parenthesized<Field>}
    }

    Field: {
        attrs:         syn::Attribute*
        vis:           syn::Visibility
        ident:         "..."
    }

    ItemEnum: {
        attrs:         syn::Attribute*
        vis:           syn::Visibility
        enum_token:    syn::token::Enum
        ident:         "..."
        variant:       Variant
    }

    Variant: {
        attrs:         syn::Attribute*
        ident:         "..."
        field:         WrappedField
    }
}

#[test]
fn compilation_test() {}
```

I get these errors however:

```rust
error: chained comparison operators require parentheses
  --> crates/derive_less/src/grammar.rs:97:1
   |
97 | }
   | ^
   |
   = help: use `::<...>` instead of `<...>` if you meant to specify type arguments
   = help: or use `(...)` if you meant to specify fn arguments

error: expected expression, found `)`
  --> crates/derive_less/src/grammar.rs:97:1
   |
97 | }
   | ^ expected expression

error: proc-macro derive produced unparseable tokens
  --> crates/derive_less/src/grammar.rs:51:1
   |
51 | / pegcel_macros::pegcel_syn! {
52 | |     use syn
53 | |
54 | |     Grammar: {
...  |
96 | |     }
97 | | }
   | |_^

error: aborting due to 3 previous errors
```

**Comment by CAD97** [comment] 2019-05-20 15:42
I think I see the issue causing `Braced<Field>` not working, if `Braced::<Field>` https://turbo.fish makes it work. I've not got a chance to investigate for a bit, but that should work in the meantime, assuming I'm correct.

In addition, you'll need to do `{&"#" syn::Attribute}`, as you need to tell Pegcel how to peek the attribute, and as `syn::Attribute` doesn't have a `Parse` impl, you'll need to make a wrapper to force choose exterior/interior attrs, I believe.

I should probably go ahead and just make a syn-ext crate with some of these helper types. (I don't want to give Pegcel's syn target a public runtime if I can avoid it.)

**Comment by CAD97** [comment] 2019-05-20 15:43
For `syn::token::*` types, you can just use the keyword inline, by the way: `"enum"` is properly translated into `Token![enum]`.

**Comment by segeljakt** [comment] 2019-05-20 18:41
I changed the code based on your feedback into this:
```rust
#![allow(clippy::eval_order_dependence)]

use {proc_macro2::TokenStream, quote::*, syn::parse::*};

#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub struct Braced<T> {
    pub brace: syn::token::Brace,
    pub value: T,
}

impl<T: Parse> Parse for Braced<T> {
    fn parse(input: ParseStream) -> Result<Self> {
        let content;
        Ok(Self {
            brace: syn::braced!(content in input),
            value: content.parse()?,
        })
    }
}

impl<T: ToTokens> ToTokens for Braced<T> {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        self.brace
            .surround(tokens, |tokens| self.value.to_tokens(tokens));
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub struct Parenthesized<T> {
    pub paren: syn::token::Paren,
    pub value: T,
}

impl<T: Parse> Parse for Parenthesized<T> {
    fn parse(input: ParseStream) -> Result<Self> {
        let content;
        Ok(Self {
            paren: syn::parenthesized!(content in input),
            value: content.parse()?,
        })
    }
}

impl<T: ToTokens> ToTokens for Parenthesized<T> {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        self.paren
            .surround(tokens, |tokens| self.value.to_tokens(tokens));
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Hash)]
struct OuterAttribute {
    attrs: Vec<syn::Attribute>,
}

impl Parse for OuterAttribute {
    fn parse(input: ParseStream) -> Result<Self> {
        Ok(Self {
            attrs: syn::Attribute::parse_outer(input)?,
        })
    }
}

impl ToTokens for OuterAttribute {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        for attr in self.attrs {
            attr.to_tokens(tokens);
        }
    }
}

pegcel_macros::pegcel_syn! {
    use syn

    Grammar: {
        templates:     Item*
        items:         syn::Item*
    }

    Item: {
        / Struct:      ItemStruct
        / Enum:        ItemEnum
    }

    ItemStruct: {
        attrs:         { &"#" OuterAttribute }*
        vis:           syn::Visibility
        struct_token:  syn::token::Struct
        ident:         "..."
        field:         WrappedField
        semi_token:    syn::token::Semi?
    }

    WrappedField: {
        / Named:       {Braced::<Field>}
        / Unnamed:     {Parenthesized::<Field>}
    }

    Field: {
        attrs:         { &"#" OuterAttribute }*
        vis:           syn::Visibility
        ident:         "..."
    }

    ItemEnum: {
        attrs:         { &"#" OuterAttribute }*
        vis:           syn::Visibility
        enum_token:    syn::token::Enum
        ident:         "..."
        variant:       Variant
    }

    Variant: {
        attrs:         { &"#" OuterAttribute }*
        ident:         "..."
        field:         WrappedField
    }
}

#[test]
fn compilation_test() {}
```
There only seems to be one kind of error left:
```
error[E0423]: expected value, found struct `ItemStruct`
  --> crates/derive_less/src/grammar.rs:81:24
   |
81 |         / Struct:      ItemStruct
   |                        ^^^^^^^^^^ did you mean `ItemStruct { /* fields */ }`?

error[E0423]: expected value, found struct `Braced`
  --> crates/derive_less/src/grammar.rs:95:25
   |
95 |         / Named:       {Braced::<Field>}
   |                         ^^^^^^^^^^^^^^^ did you mean `Braced { /* fields */ }`?

error: aborting due to 2 previous errors
```

**Comment by segeljakt** [comment] 2019-05-20 18:48
`Token![...]` appears to not work for me also:

```
error: expected one of: curly braces, string literal, identifier
  --> crates/derive_less/src/grammar.rs:88:35
   |
88 |         struct_token:  syn::Token![struct]
   |                                   ^^^^^^^^

error: aborting due to previous error
```

**Comment by CAD97** [comment] 2019-05-20 19:18
I see the issue:

For the second: you just want to do `struct_token: "struct"`. This should be translated properly.

For the first: The problem is that Pegcel is trying to peek for an `ItemStruct` at the head of the parse stream, when it's not a peekable token.

[See how Syn does `Item` parsing here.](https://docs.rs/syn/0.15.34/src/syn/item.rs.html#768-869) They go far beyond the standard LL(3) parsing to LL(*) here to determine what kind of item they're parsing.

For your use case, it looks like barring further improvement to Syn and Pegcel to support speculative parsing (and thus proper PEG, not just an LL(3) PEG-like that I have right now), you'll need something like the following:

```rust
#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub enum Item {
    Struct(ItemStruct),
    Enum(ItemEnum),
}

impl ::syn::parse::Parse for Item {
    fn parse(input: ::syn::parse::ParseStream) -> ::syn::parse::Result<Self> {
        let ahead = input.fork();
        ahead.call(Attribute::parse_outer)?;
        let vis: Visibility = ahead.parse()?;

        let lookahead = ahead.lookahead1();
        if lookahead.peek(Token![struct]) {
           input.parse().map(Item::Struct)
        } else if lookahead.peek(Token![enum]) {
            input.parse().map(Item::Enum)
        } else {
            Err(lookahead.error())
        }
    }
}

impl ::quote::ToTokens for Item {
    fn to_tokens(&self, tokens: &mut ::proc_macro2::TokenStream) {
        use ::quote::{ToTokens, TokenStreamExt};
        match self {
            Item::Struct(s) => s.to_tokens(tokens),
            Item::Enum(e) => e.to_tokens(tokens),
        }
    }
}
```

You'll also need a peek `&syn::token::Brace` for the enum variant that starts with a `Braced`, so that the lookahead can determine what to do here.

Modifying the Rust grammar slightly is basically the hardest stress test available, so thanks for taking Pegcel out for a test drive <3

Compiling version:

<details>

```rust
#![allow(clippy::eval_order_dependence)]

use {proc_macro2::TokenStream, quote::*, syn::parse::*};

#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub struct Braced<T> {
    pub brace: syn::token::Brace,
    pub value: T,
}

impl<T: Parse> Parse for Braced<T> {
    fn parse(input: ParseStream) -> Result<Self> {
        let content;
        Ok(Self {
            brace: syn::braced!(content in input),
            value: content.parse()?,
        })
    }
}

impl<T: ToTokens> ToTokens for Braced<T> {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        self.brace
            .surround(tokens, |tokens| self.value.to_tokens(tokens));
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub struct Parenthesized<T> {
    pub paren: syn::token::Paren,
    pub value: T,
}

impl<T: Parse> Parse for Parenthesized<T> {
    fn parse(input: ParseStream) -> Result<Self> {
        let content;
        Ok(Self {
            paren: syn::parenthesized!(content in input),
            value: content.parse()?,
        })
    }
}

impl<T: ToTokens> ToTokens for Parenthesized<T> {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        self.paren
            .surround(tokens, |tokens| self.value.to_tokens(tokens));
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub struct OuterAttribute {
    attrs: Vec<syn::Attribute>,
}

impl Parse for OuterAttribute {
    fn parse(input: ParseStream) -> Result<Self> {
        Ok(Self {
            attrs: syn::Attribute::parse_outer(input)?,
        })
    }
}

impl ToTokens for OuterAttribute {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        for attr in &self.attrs {
            attr.to_tokens(tokens);
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub enum Item {
    Struct(ItemStruct),
    Enum(ItemEnum),
}

impl ::syn::parse::Parse for Item {
    fn parse(input: ::syn::parse::ParseStream) -> ::syn::parse::Result<Self> {
        let ahead = input.fork();
        ahead.call(syn::Attribute::parse_outer)?;
        let vis: syn::Visibility = ahead.parse()?;

        let lookahead = ahead.lookahead1();
        if lookahead.peek(Token![struct]) {
            input.parse().map(Item::Struct)
        } else if lookahead.peek(Token![enum]) {
            input.parse().map(Item::Enum)
        } else {
            Err(lookahead.error())
        }
    }
}

impl ::quote::ToTokens for Item {
    fn to_tokens(&self, tokens: &mut ::proc_macro2::TokenStream) {
        use ::quote::{ToTokens, TokenStreamExt};
        match self {
            Item::Struct(s) => s.to_tokens(tokens),
            Item::Enum(e) => e.to_tokens(tokens),
        }
    }
}

pegcel_macros::pegcel_syn! {
    use syn

    Grammar: {
        templates:     Item*
        items:         syn::Item*
    }

    ItemStruct: {
        attrs:         { &"#" OuterAttribute }*
        vis:           syn::Visibility
        struct_token:  "struct"
        ident:         "..."
        field:         WrappedField
        semi_token:    syn::token::Semi?
    }

    WrappedField: {
        / Named:       {&syn::token::Brace Braced::<Field>}
        / Unnamed:     {Parenthesized::<Field>}
    }

    Field: {
        attrs:         { &"#" OuterAttribute }*
        vis:           syn::Visibility
        ident:         "..."
    }

    ItemEnum: {
        attrs:         { &"#" OuterAttribute }*
        vis:           syn::Visibility
        enum_token:    "enum"
        ident:         "..."
        variant:       Variant
    }

    Variant: {
        attrs:         { &"#" OuterAttribute }*
        ident:         "..."
        field:         WrappedField
    }
}

#[test]
fn compilation_test() {}
```
</details>

I'm uncertain how best to address the silent problem here, though (and it's a bug that Pegcel allows this): `Grammar`. Here's the `Parse` impl (manually cleaned), see the issue?

```rust
impl ::syn::parse::Parse for Grammar {
    fn parse(input: ::syn::parse::ParseStream) -> ::syn::parse::Result<Self> {
        let mut templates = vec![];
        while !input.is_empty() {
            let template = input.parse()?;
            templates.push(template);
        }

        let mut items = vec![];
        while !input.is_empty() {
            let item = input.parse()?;
            items.push(item);
        }

        Ok(Grammar { templates, items })
    }
}
```

This will need to do the same song and dance of the extended fork peek to determine if the item looks like your item or a "real" item, then put it in the correct bin.

That would look something like:

```rust
    while !input.is_empty() {
        let ahead = input.fork();
        ahead.call(syn::Attribute::parse_outer)?;
        let vis: syn::Visibility = ahead.parse()?;

        if ahead.peek(Token![struct]) && ahead.peek2(Token![...]) {
            templates.push(Item::Struct(input.parse()?));
        } else if lookahead.peek(Token![enum]) && ahead.peek2(Token![...]) {
            templates.push(Item::Enum(input.parse()?));
        } else {
            items.push(input.parse()?);
        }
    }
```

**Comment by segeljakt** [comment] 2019-05-21 08:09
Ok, sweet, I will continue testing

**Comment by CAD97** [comment] 2022-07-25 05:08
Closing; I have a very different design going for v0.2 now

**Closed as completed by CAD97** 2022-07-25 05:08 UTC
